kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx-deployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # Allow up to seven pods to be running during the update process
      maxSurge: 2
      # Require at least four pods to be running during the update process
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          # Updated deployment uses more modern nginx image
          image: nginx:1.15.0 
