kind: ConfigMap
apiVersion: v1
metadata:
  name: example-configmap
data:
  # Configuration values can be set as key-value properties
  database: mongodb
  database_uri: http://localhost:27017
  
  # Or set like a file
  keys: |
    image.public.key=771
    rsa.public.key=42
