kind: Pod
apiVersion: v1
metadata:
  name: pod-using-secret
spec:
  # Add the Secret as a volume to the Pod
  volumes:
    # `name` here must match the name 
    # specified in the volume mount
    - name: api-secret-volume 
      # Populate the volume with config map data
      secret:
        # `secretName` here must match the name 
        # specified in the secret's YAML
        secretName: api-authentication-secret
        
  containers:
    - name: container-secret
      image: nginx:1.7.9
      volumeMounts:
        # `name` here must match the name 
        # from the volumes section of this pod
        - name: api-secret-volume
          mountPath: /etc/secret
