kind: Pod
apiVersion: v1
metadata:
  name: use-service-account-pod
  namespace: ckad
spec:
  serviceAccountName: my-service-account
  containers:
    - name: container-service-account
      image: nginx:1.7.9
      
